"""Initial migration

Revision ID: 94fe0c1c096e
Revises: 
Create Date: 2025-12-29 17:16:42.565429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fe0c1c096e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('period_type', sa.Enum('DAY', 'WEEK', 'MONTH', name='periodtype'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_period_end'), 'report_snapshots', ['period_end'], unique=False)
    op.create_index(op.f('ix_report_snapshots_period_start'), 'report_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_report_snapshots_period_type'), 'report_snapshots', ['period_type'], unique=False)
    op.create_index(op.f('ix_report_snapshots_tenant_id'), 'report_snapshots', ['tenant_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_policies_tenant_id'), 'sla_policies', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TENANT_ADMIN', 'CALL_CENTER', 'AS_MANAGER', 'AS_ENGINEER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('chargers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('csms_charger_id', sa.String(), nullable=True),
    sa.Column('ocpp_protocol', sa.String(), nullable=True),
    sa.Column('power_kw', sa.Integer(), nullable=True),
    sa.Column('connector_count', sa.Integer(), nullable=True),
    sa.Column('connector_types', sa.JSON(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('last_status_update', sa.DateTime(), nullable=True),
    sa.Column('charger_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargers_csms_charger_id'), 'chargers', ['csms_charger_id'], unique=True)
    op.create_index(op.f('ix_chargers_serial_number'), 'chargers', ['serial_number'], unique=True)
    op.create_index(op.f('ix_chargers_site_id'), 'chargers', ['site_id'], unique=False)
    op.create_index(op.f('ix_chargers_tenant_id'), 'chargers', ['tenant_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('charger_id', sa.String(), nullable=True),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel', sa.Enum('PHONE', 'EMAIL', 'WEB', 'MOBILE', 'AUTO', name='ticketchannel'), nullable=False),
    sa.Column('category', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'POWER', 'CONNECTOR', 'FIRMWARE', 'OTHER', name='ticketcategory'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='ticketpriority'), nullable=False),
    sa.Column('current_status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_CUSTOMER', 'PENDING_VENDOR', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=True),
    sa.Column('reporter_email', sa.String(), nullable=True),
    sa.Column('reporter_phone', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_charger_id'), 'tickets', ['charger_id'], unique=False)
    op.create_index(op.f('ix_tickets_closed_at'), 'tickets', ['closed_at'], unique=False)
    op.create_index(op.f('ix_tickets_current_status'), 'tickets', ['current_status'], unique=False)
    op.create_index(op.f('ix_tickets_opened_at'), 'tickets', ['opened_at'], unique=False)
    op.create_index(op.f('ix_tickets_site_id'), 'tickets', ['site_id'], unique=False)
    op.create_index(op.f('ix_tickets_sla_breached'), 'tickets', ['sla_breached'], unique=False)
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('assignee_type', sa.Enum('USER', 'VENDOR', name='assigneetype'), nullable=False),
    sa.Column('assignee_user_id', sa.String(), nullable=True),
    sa.Column('assignee_vendor_name', sa.String(), nullable=True),
    sa.Column('assignee_vendor_contact', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assigned_at'), 'assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_assignments_assignee_user_id'), 'assignments', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_assignments_due_at'), 'assignments', ['due_at'], unique=False)
    op.create_index(op.f('ix_assignments_ticket_id'), 'assignments', ['ticket_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_created_at'), 'attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_attachments_tenant_id'), 'attachments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attachments_ticket_id'), 'attachments', ['ticket_id'], unique=False)
    op.create_table('csms_event_refs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('charger_id', sa.String(), nullable=False),
    sa.Column('csms_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csms_event_refs_charger_id'), 'csms_event_refs', ['charger_id'], unique=False)
    op.create_index(op.f('ix_csms_event_refs_csms_event_id'), 'csms_event_refs', ['csms_event_id'], unique=False)
    op.create_index(op.f('ix_csms_event_refs_occurred_at'), 'csms_event_refs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_csms_event_refs_ticket_id'), 'csms_event_refs', ['ticket_id'], unique=False)
    op.create_table('firmware_job_refs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('charger_id', sa.String(), nullable=False),
    sa.Column('csms_job_id', sa.String(), nullable=False),
    sa.Column('target_version', sa.String(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('last_status', sa.Enum('REQUESTED', 'SCHEDULED', 'DOWNLOADING', 'DOWNLOADED', 'INSTALLING', 'INSTALLED', 'FAILED', 'CANCELLED', name='firmwarejobstatus'), nullable=False),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_job_refs_charger_id'), 'firmware_job_refs', ['charger_id'], unique=False)
    op.create_index(op.f('ix_firmware_job_refs_csms_job_id'), 'firmware_job_refs', ['csms_job_id'], unique=False)
    op.create_index(op.f('ix_firmware_job_refs_ticket_id'), 'firmware_job_refs', ['ticket_id'], unique=False)
    op.create_table('sla_measurements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MET', 'BREACHED', 'CANCELLED', name='slastatus'), nullable=False),
    sa.Column('response_target_at', sa.DateTime(), nullable=False),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('response_breached', sa.Boolean(), nullable=False),
    sa.Column('resolution_target_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_breached', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('breached_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['sla_policies.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_measurements_status'), 'sla_measurements', ['status'], unique=False)
    op.create_index(op.f('ix_sla_measurements_ticket_id'), 'sla_measurements', ['ticket_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_CUSTOMER', 'PENDING_VENDOR', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticketstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_CUSTOMER', 'PENDING_VENDOR', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_history_changed_at'), 'ticket_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    op.create_table('worklogs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('work_type', sa.Enum('DIAGNOSIS', 'REPAIR', 'TESTING', 'COMMUNICATION', 'TRAVEL', 'WAITING', 'OTHER', name='worktype'), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('is_internal', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worklogs_created_at'), 'worklogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_worklogs_ticket_id'), 'worklogs', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worklogs_ticket_id'), table_name='worklogs')
    op.drop_index(op.f('ix_worklogs_created_at'), table_name='worklogs')
    op.drop_table('worklogs')
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_changed_at'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_sla_measurements_ticket_id'), table_name='sla_measurements')
    op.drop_index(op.f('ix_sla_measurements_status'), table_name='sla_measurements')
    op.drop_table('sla_measurements')
    op.drop_index(op.f('ix_firmware_job_refs_ticket_id'), table_name='firmware_job_refs')
    op.drop_index(op.f('ix_firmware_job_refs_csms_job_id'), table_name='firmware_job_refs')
    op.drop_index(op.f('ix_firmware_job_refs_charger_id'), table_name='firmware_job_refs')
    op.drop_table('firmware_job_refs')
    op.drop_index(op.f('ix_csms_event_refs_ticket_id'), table_name='csms_event_refs')
    op.drop_index(op.f('ix_csms_event_refs_occurred_at'), table_name='csms_event_refs')
    op.drop_index(op.f('ix_csms_event_refs_csms_event_id'), table_name='csms_event_refs')
    op.drop_index(op.f('ix_csms_event_refs_charger_id'), table_name='csms_event_refs')
    op.drop_table('csms_event_refs')
    op.drop_index(op.f('ix_attachments_ticket_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_tenant_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_created_at'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_assignments_ticket_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_due_at'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignee_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_at'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sla_breached'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_site_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_opened_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_current_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_closed_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_charger_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_chargers_tenant_id'), table_name='chargers')
    op.drop_index(op.f('ix_chargers_site_id'), table_name='chargers')
    op.drop_index(op.f('ix_chargers_serial_number'), table_name='chargers')
    op.drop_index(op.f('ix_chargers_csms_charger_id'), table_name='chargers')
    op.drop_table('chargers')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sla_policies_tenant_id'), table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_report_snapshots_tenant_id'), table_name='report_snapshots')
    op.drop_index(op.f('ix_report_snapshots_period_type'), table_name='report_snapshots')
    op.drop_index(op.f('ix_report_snapshots_period_start'), table_name='report_snapshots')
    op.drop_index(op.f('ix_report_snapshots_period_end'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
